// App Store Connect territory codes, names, and currencies.
// Source: Apple App Store Connect API territory list.

export const TERRITORIES = [
  { code: "ABW", name: "Aruba", currency: "USD" },
  { code: "AFG", name: "Afghanistan", currency: "USD" },
  { code: "AGO", name: "Angola", currency: "USD" },
  { code: "AIA", name: "Anguilla", currency: "USD" },
  { code: "ALB", name: "Albania", currency: "USD" },
  { code: "AND", name: "Andorra", currency: "EUR" },
  { code: "ANT", name: "Netherlands Antilles", currency: "USD" },
  { code: "ARE", name: "United Arab Emirates", currency: "AED" },
  { code: "ARG", name: "Argentina", currency: "USD" },
  { code: "ARM", name: "Armenia", currency: "USD" },
  { code: "ATG", name: "Antigua and Barbuda", currency: "USD" },
  { code: "AUS", name: "Australia", currency: "AUD" },
  { code: "AUT", name: "Austria", currency: "EUR" },
  { code: "AZE", name: "Azerbaijan", currency: "USD" },
  { code: "BEL", name: "Belgium", currency: "EUR" },
  { code: "BEN", name: "Benin", currency: "USD" },
  { code: "BFA", name: "Burkina Faso", currency: "USD" },
  { code: "BGD", name: "Bangladesh", currency: "USD" },
  { code: "BGR", name: "Bulgaria", currency: "BGN" },
  { code: "BHR", name: "Bahrain", currency: "USD" },
  { code: "BHS", name: "Bahamas", currency: "USD" },
  { code: "BIH", name: "Bosnia and Herzegovina", currency: "USD" },
  { code: "BLR", name: "Belarus", currency: "USD" },
  { code: "BLZ", name: "Belize", currency: "USD" },
  { code: "BMU", name: "Bermuda", currency: "USD" },
  { code: "BOL", name: "Bolivia", currency: "USD" },
  { code: "BRA", name: "Brazil", currency: "BRL" },
  { code: "BRB", name: "Barbados", currency: "USD" },
  { code: "BRN", name: "Brunei", currency: "USD" },
  { code: "BTN", name: "Bhutan", currency: "USD" },
  { code: "BWA", name: "Botswana", currency: "USD" },
  { code: "CAF", name: "Central African Republic", currency: "USD" },
  { code: "CAN", name: "Canada", currency: "CAD" },
  { code: "CHE", name: "Switzerland", currency: "CHF" },
  { code: "CHL", name: "Chile", currency: "CLP" },
  { code: "CHN", name: "China mainland", currency: "CNY" },
  { code: "CIV", name: "Cote d'Ivoire", currency: "USD" },
  { code: "CMR", name: "Cameroon", currency: "USD" },
  { code: "COD", name: "Congo, Democratic Republic", currency: "USD" },
  { code: "COG", name: "Congo, Republic", currency: "USD" },
  { code: "COL", name: "Colombia", currency: "COP" },
  { code: "CPV", name: "Cape Verde", currency: "USD" },
  { code: "CRI", name: "Costa Rica", currency: "USD" },
  { code: "CYM", name: "Cayman Islands", currency: "USD" },
  { code: "CYP", name: "Cyprus", currency: "EUR" },
  { code: "CZE", name: "Czech Republic", currency: "CZK" },
  { code: "DEU", name: "Germany", currency: "EUR" },
  { code: "DMA", name: "Dominica", currency: "USD" },
  { code: "DNK", name: "Denmark", currency: "DKK" },
  { code: "DOM", name: "Dominican Republic", currency: "USD" },
  { code: "DZA", name: "Algeria", currency: "USD" },
  { code: "ECU", name: "Ecuador", currency: "USD" },
  { code: "EGY", name: "Egypt", currency: "EGP" },
  { code: "ESP", name: "Spain", currency: "EUR" },
  { code: "EST", name: "Estonia", currency: "EUR" },
  { code: "ETH", name: "Ethiopia", currency: "USD" },
  { code: "FIN", name: "Finland", currency: "EUR" },
  { code: "FJI", name: "Fiji", currency: "USD" },
  { code: "FRA", name: "France", currency: "EUR" },
  { code: "FSM", name: "Micronesia", currency: "USD" },
  { code: "GAB", name: "Gabon", currency: "USD" },
  { code: "GBR", name: "United Kingdom", currency: "GBP" },
  { code: "GEO", name: "Georgia", currency: "USD" },
  { code: "GHA", name: "Ghana", currency: "USD" },
  { code: "GIN", name: "Guinea", currency: "USD" },
  { code: "GMB", name: "Gambia", currency: "USD" },
  { code: "GNB", name: "Guinea-Bissau", currency: "USD" },
  { code: "GRC", name: "Greece", currency: "EUR" },
  { code: "GRD", name: "Grenada", currency: "USD" },
  { code: "GTM", name: "Guatemala", currency: "USD" },
  { code: "GUY", name: "Guyana", currency: "USD" },
  { code: "HKG", name: "Hong Kong", currency: "HKD" },
  { code: "HND", name: "Honduras", currency: "USD" },
  { code: "HRV", name: "Croatia", currency: "EUR" },
  { code: "HUN", name: "Hungary", currency: "HUF" },
  { code: "IDN", name: "Indonesia", currency: "IDR" },
  { code: "IND", name: "India", currency: "INR" },
  { code: "IRL", name: "Ireland", currency: "EUR" },
  { code: "IRQ", name: "Iraq", currency: "USD" },
  { code: "ISL", name: "Iceland", currency: "USD" },
  { code: "ISR", name: "Israel", currency: "ILS" },
  { code: "ITA", name: "Italy", currency: "EUR" },
  { code: "JAM", name: "Jamaica", currency: "USD" },
  { code: "JOR", name: "Jordan", currency: "USD" },
  { code: "JPN", name: "Japan", currency: "JPY" },
  { code: "KAZ", name: "Kazakhstan", currency: "KZT" },
  { code: "KEN", name: "Kenya", currency: "KES" },
  { code: "KGZ", name: "Kyrgyzstan", currency: "USD" },
  { code: "KHM", name: "Cambodia", currency: "USD" },
  { code: "KNA", name: "St. Kitts and Nevis", currency: "USD" },
  { code: "KOR", name: "South Korea", currency: "KRW" },
  { code: "KWT", name: "Kuwait", currency: "USD" },
  { code: "LAO", name: "Laos", currency: "USD" },
  { code: "LBN", name: "Lebanon", currency: "USD" },
  { code: "LBR", name: "Liberia", currency: "USD" },
  { code: "LBY", name: "Libya", currency: "USD" },
  { code: "LCA", name: "St. Lucia", currency: "USD" },
  { code: "LKA", name: "Sri Lanka", currency: "USD" },
  { code: "LTU", name: "Lithuania", currency: "EUR" },
  { code: "LUX", name: "Luxembourg", currency: "EUR" },
  { code: "LVA", name: "Latvia", currency: "EUR" },
  { code: "MAC", name: "Macao", currency: "USD" },
  { code: "MAR", name: "Morocco", currency: "USD" },
  { code: "MDA", name: "Moldova", currency: "USD" },
  { code: "MDG", name: "Madagascar", currency: "USD" },
  { code: "MDV", name: "Maldives", currency: "USD" },
  { code: "MEX", name: "Mexico", currency: "MXN" },
  { code: "MKD", name: "North Macedonia", currency: "USD" },
  { code: "MLI", name: "Mali", currency: "USD" },
  { code: "MLT", name: "Malta", currency: "EUR" },
  { code: "MMR", name: "Myanmar", currency: "USD" },
  { code: "MNE", name: "Montenegro", currency: "EUR" },
  { code: "MNG", name: "Mongolia", currency: "USD" },
  { code: "MOZ", name: "Mozambique", currency: "USD" },
  { code: "MRT", name: "Mauritania", currency: "USD" },
  { code: "MSR", name: "Montserrat", currency: "USD" },
  { code: "MUS", name: "Mauritius", currency: "USD" },
  { code: "MWI", name: "Malawi", currency: "USD" },
  { code: "MYS", name: "Malaysia", currency: "MYR" },
  { code: "NAM", name: "Namibia", currency: "USD" },
  { code: "NER", name: "Niger", currency: "USD" },
  { code: "NGA", name: "Nigeria", currency: "NGN" },
  { code: "NIC", name: "Nicaragua", currency: "USD" },
  { code: "NLD", name: "Netherlands", currency: "EUR" },
  { code: "NOR", name: "Norway", currency: "NOK" },
  { code: "NPL", name: "Nepal", currency: "USD" },
  { code: "NRU", name: "Nauru", currency: "USD" },
  { code: "NZL", name: "New Zealand", currency: "NZD" },
  { code: "OMN", name: "Oman", currency: "USD" },
  { code: "PAK", name: "Pakistan", currency: "PKR" },
  { code: "PAN", name: "Panama", currency: "USD" },
  { code: "PER", name: "Peru", currency: "PEN" },
  { code: "PHL", name: "Philippines", currency: "PHP" },
  { code: "PLW", name: "Palau", currency: "USD" },
  { code: "PNG", name: "Papua New Guinea", currency: "USD" },
  { code: "POL", name: "Poland", currency: "PLN" },
  { code: "PRT", name: "Portugal", currency: "EUR" },
  { code: "PRY", name: "Paraguay", currency: "USD" },
  { code: "PSE", name: "Palestinian Authority", currency: "USD" },
  { code: "QAT", name: "Qatar", currency: "QAR" },
  { code: "ROU", name: "Romania", currency: "RON" },
  { code: "RUS", name: "Russia", currency: "RUB" },
  { code: "RWA", name: "Rwanda", currency: "USD" },
  { code: "SAU", name: "Saudi Arabia", currency: "SAR" },
  { code: "SEN", name: "Senegal", currency: "USD" },
  { code: "SGP", name: "Singapore", currency: "SGD" },
  { code: "SLB", name: "Solomon Islands", currency: "USD" },
  { code: "SLE", name: "Sierra Leone", currency: "USD" },
  { code: "SLV", name: "El Salvador", currency: "USD" },
  { code: "SRB", name: "Serbia", currency: "USD" },
  { code: "STP", name: "Sao Tome and Principe", currency: "USD" },
  { code: "SUR", name: "Suriname", currency: "USD" },
  { code: "SVK", name: "Slovakia", currency: "EUR" },
  { code: "SVN", name: "Slovenia", currency: "EUR" },
  { code: "SWE", name: "Sweden", currency: "SEK" },
  { code: "SWZ", name: "Eswatini", currency: "USD" },
  { code: "SYC", name: "Seychelles", currency: "USD" },
  { code: "TCA", name: "Turks and Caicos", currency: "USD" },
  { code: "TCD", name: "Chad", currency: "USD" },
  { code: "TGO", name: "Togo", currency: "USD" },
  { code: "THA", name: "Thailand", currency: "THB" },
  { code: "TJK", name: "Tajikistan", currency: "USD" },
  { code: "TKM", name: "Turkmenistan", currency: "USD" },
  { code: "TON", name: "Tonga", currency: "USD" },
  { code: "TTO", name: "Trinidad and Tobago", currency: "USD" },
  { code: "TUN", name: "Tunisia", currency: "USD" },
  { code: "TUR", name: "Turkey", currency: "TRY" },
  { code: "TWN", name: "Taiwan", currency: "TWD" },
  { code: "TZA", name: "Tanzania", currency: "TZS" },
  { code: "UGA", name: "Uganda", currency: "USD" },
  { code: "UKR", name: "Ukraine", currency: "USD" },
  { code: "URY", name: "Uruguay", currency: "USD" },
  { code: "USA", name: "United States", currency: "USD" },
  { code: "UZB", name: "Uzbekistan", currency: "USD" },
  { code: "VCT", name: "St. Vincent and the Grenadines", currency: "USD" },
  { code: "VEN", name: "Venezuela", currency: "USD" },
  { code: "VGB", name: "British Virgin Islands", currency: "USD" },
  { code: "VNM", name: "Vietnam", currency: "VND" },
  { code: "VUT", name: "Vanuatu", currency: "USD" },
  { code: "YEM", name: "Yemen", currency: "USD" },
  { code: "ZAF", name: "South Africa", currency: "ZAR" },
  { code: "ZMB", name: "Zambia", currency: "USD" },
  { code: "ZWE", name: "Zimbabwe", currency: "USD" },
];

export const TERRITORY_MAP = new Map(TERRITORIES.map((t) => [t.code, t]));
